// Pure local rules and heuristics. The public state never exposes computer hands.
export const CARD_GAME_RULES={
 doudizhu:{title:'斗地主',titleEn:'Dou Dizhu',rules:['一副54张牌，三人各17张；地主获得3张公开底牌并先出。先出完的一方获胜，两位农民合作。','轮流叫或不叫；都不叫时由电脑承接地主。不计钱、不计分。','支持单、对、三张、三带一/对、顺子、连对、飞机及翅膀、四带二/两对、炸弹、王炸。顺子主体不能含2或王。','单翼可由对子拆成两张；翅膀不可含主体点数、完整炸弹或双王。四带二不是炸弹。两家连续过牌后，最后出牌者重新领出。'],rulesEn:['54 cards: 17 each, plus three public bottom cards for the landlord, who leads. The landlord plays against two cooperating farmers. The first side to empty a hand wins.','Take turns calling or declining. If everyone declines, a computer takes the landlord role. No money or scoring.','Singles, pairs, triples, triple attachments, straights, consecutive pairs, airplanes and wings, four with two, bombs and the rocket are supported. Sequence bodies stop at A.','Single wings may include a pair, but not body ranks, a whole bomb or both jokers. Four with two is not a bomb. Two consecutive passes return the lead to the last player.'],sources:[{title:'JJ 官方斗地主规则',url:'https://www.jj.cn/news/320/20110920103700018196.shtml'}]},
 mahjong:{title:'家常四人麻将',titleEn:'Home Mahjong',rules:['136张无花牌，真人与三位电脑。庄家14张先打，其余13张；以后先摸后打。','只可吃上家的牌；碰、明杠和胡可以取任何人的最新弃牌。胡优先于碰/杠，碰/杠优先于吃；同级按出牌者之后的座次优先。','可暗杠或给已有碰牌加杠，杠后从牌墙尾补牌。加杠允许抢杠胡；不抢暗杠，不设独立牌尾保留区。','普通四面子一将、七对（四张可作两对）及十三幺可以胡。无起胡番数、无立直、无宝牌、无积分；一人胡即结束，牌墙用尽荒庄。'],rulesEn:['136 tiles, no flowers. You play three computers. The dealer starts with 14 tiles, others with 13; subsequently draw before discarding.','Chow only the previous player; pung, exposed kong or win on any latest discard. Win has priority over pung/kong, then chow. Equal priority follows seat order after the discarder.','Concealed and added kongs are allowed, with a replacement drawn from the wall tail. An added kong can be robbed for a win; concealed kongs cannot. There is no separate dead wall.','Win with four melds and a pair, seven pairs (a quad may count as two pairs), or thirteen orphans. No minimum fan, riichi, dora or scoring. One winner ends the hand; an empty wall is a draw.'],sources:[{title:'Mahjong International League — Official International Rules guide',url:'https://mahjong-mil.org/wp-content/uploads/2024/08/A_GUIDE_TO_MAHJONG.pdf'}]}
};
const clone=value=>structuredClone(value);
const shuffle=(values,random)=>{const result=[...values];for(let i=result.length-1;i>0;i--){const r=Number(random()),j=Math.floor(Math.min(.999999,Math.max(0,Number.isFinite(r)?r:.5))*(i+1));[result[i],result[j]]=[result[j],result[i]];}return result;};
const rankLabel=rank=>({11:'J',12:'Q',13:'K',14:'A',15:'2',16:'小王',17:'大王'})[rank]||String(rank);
export const makeDoudizhuDeck=()=>Array.from({length:54},(_,id)=>{const rank=id<52?3+Math.floor(id/4):id-36,suit=id<52?['♣','♦','♥','♠'][id%4]:'';return {id,rank,suit,label:rank<16?suit+rankLabel(rank):rankLabel(rank),labelEn:rank===16?'Small joker':rank===17?'Big joker':suit+rankLabel(rank),red:suit==='♦'||suit==='♥'||rank===17};});
const cardSort=(a,b)=>a.rank-b.rank||a.id-b.id;
const groupRanks=cards=>{const map=new Map();for(const card of [...cards].sort(cardSort)){if(!map.has(card.rank))map.set(card.rank,[]);map.get(card.rank).push(card);}return map;};
const consecutive=ranks=>ranks.every((r,i)=>r<=14&&(!i||r===ranks[i-1]+1));
const DDZ_NAMES={single:['单张','Single'],pair:['对子','Pair'],triple:['三张','Triple'],'triple-single':['三带一','Triple + single'],'triple-pair':['三带对','Triple + pair'],straight:['顺子','Straight'],'pair-run':['连对','Consecutive pairs'],airplane:['飞机','Airplane'],'airplane-single':['飞机带单','Airplane + singles'],'airplane-pair':['飞机带对','Airplane + pairs'],'four-single':['四带二','Four + two singles'],'four-pair':['四带两对','Four + two pairs'],bomb:['炸弹','Bomb'],rocket:['王炸','Rocket']};

export function classifyDoudizhu(cards){
 if(!Array.isArray(cards)||!cards.length||cards.length>20||cards.some(c=>!Number.isInteger(c.rank)||c.rank<3||c.rank>17)||new Set(cards.map(c=>c.id)).size!==cards.length)return null;
 const groups=groupRanks(cards),ranks=[...groups.keys()],counts=ranks.map(r=>groups.get(r).length),size=cards.length;
 if(ranks.some(r=>groups.get(r).length>(r>=16?1:4)))return null;
 const result=(type,key,chain=1)=>({type,key,chain,size,name:DDZ_NAMES[type][0],nameEn:DDZ_NAMES[type][1]});
 if(size===2&&ranks.join(',')==='16,17')return result('rocket',17);
 if(ranks.length===1&&size<=4)return result(['','single','pair','triple','bomb'][size],ranks[0]);
 if(size===4&&counts.includes(3))return result('triple-single',ranks[counts.indexOf(3)]);
 if(size===5&&counts.includes(3)&&counts.includes(2))return result('triple-pair',ranks[counts.indexOf(3)]);
 if(size>=5&&counts.every(c=>c===1)&&consecutive(ranks))return result('straight',ranks.at(-1),size);
 if(size>=6&&size%2===0&&counts.every(c=>c===2)&&consecutive(ranks))return result('pair-run',ranks.at(-1),size/2);
 if(size>=6&&size%3===0&&counts.every(c=>c===3)&&consecutive(ranks))return result('airplane',ranks.at(-1),size/3);
 const validSingles=(rest,total)=>[...rest.values()].reduce((sum,n)=>sum+n,0)===total&&[...rest.values()].every(n=>n<=2)&&!(rest.has(16)&&rest.has(17));
 if([6,8].includes(size)&&counts.includes(4))for(const rank of ranks.filter(r=>groups.get(r).length===4)){const rest=new Map(ranks.filter(r=>r!==rank).map(r=>[r,groups.get(r).length]));if(size===6&&validSingles(rest,2))return result('four-single',rank);if(size===8&&rest.size===2&&[...rest.values()].every(n=>n===2))return result('four-pair',rank);}
 for(const [type,mult] of [['airplane-single',4],['airplane-pair',5]]){
  if(size%mult)continue;const n=size/mult;if(n<2)continue;
  for(let start=3;start+n-1<=14;start++){const body=Array.from({length:n},(_,i)=>start+i);if(!body.every(r=>groups.get(r)?.length===3))continue;const rest=new Map(ranks.filter(r=>!body.includes(r)).map(r=>[r,groups.get(r).length]));if(type==='airplane-single'?validSingles(rest,n):rest.size===n&&[...rest.values()].every(c=>c===2))return result(type,start+n-1,n);}
 }
 return null;
}
export function beatsDoudizhu(candidate,target){if(!candidate)return false;if(!target)return true;if(target.type==='rocket')return false;if(candidate.type==='rocket')return true;if(candidate.type==='bomb')return target.type!=='bomb'||candidate.key>target.key;if(target.type==='bomb')return false;return candidate.type===target.type&&candidate.size===target.size&&candidate.chain===target.chain&&candidate.key>target.key;}
function chooseAttachments(groups,count,pairs=false){const entries=[...groups.entries()],result=[];function visit(index,left,cards){if(left===0){result.push(cards);return;}if(index>=entries.length)return;const [,values]=entries[index];visit(index+1,left,cards);const max=pairs?(values.length>=2?1:0):Math.min(2,values.length,left);for(let n=1;n<=Math.min(left,max);n++)visit(index+1,left-n,[...cards,...values.slice(0,pairs?2:n)]);}visit(0,count,[]);return result;}
export function legalDoudizhuPlays(hand,target=null){
 const groups=groupRanks(hand),plays=new Map();
 function add(cards){const pattern=classifyDoudizhu(cards);if(!pattern||!beatsDoudizhu(pattern,target))return;const cardIds=cards.map(c=>c.id).sort((a,b)=>a-b),key=cardIds.join(',');if(!plays.has(key))plays.set(key,{type:'play',cardIds,pattern,label:pattern.name,labelEn:pattern.nameEn});}
 for(const [rank,cards] of groups){for(let n=1;n<=Math.min(4,cards.length);n++)add(cards.slice(0,n));if(cards.length>=3)for(const [other,values] of groups)if(other!==rank){add([...cards.slice(0,3),values[0]]);if(values.length>=2)add([...cards.slice(0,3),...values.slice(0,2)]);}if(cards.length===4){const rest=new Map([...groups].filter(([r])=>r!==rank));for(const extra of chooseAttachments(rest,2))add([...cards,...extra]);for(const extra of chooseAttachments(rest,2,true))add([...cards,...extra]);}}
 if(groups.has(16)&&groups.has(17))add([groups.get(16)[0],groups.get(17)[0]]);
 for(const [multiplicity,min] of [[1,5],[2,3],[3,2]])for(let start=3;start<=14;start++){
  const body=[];for(let end=start;end<=14;end++){if((groups.get(end)?.length||0)<multiplicity)break;body.push(...groups.get(end).slice(0,multiplicity));const length=end-start+1;if(length<min)continue;add(body);if(multiplicity===3){const rest=new Map([...groups].filter(([r])=>r<start||r>end));if(body.length+length<=hand.length)for(const extra of chooseAttachments(rest,length))add([...body,...extra]);if(body.length+length*2<=hand.length)for(const extra of chooseAttachments(rest,length,true))add([...body,...extra]);}}
 }
 return [...plays.values()].sort((a,b)=>a.cardIds.length-b.cardIds.length||a.pattern.key-b.pattern.key);
}
function ddzStrength(hand){const groups=groupRanks(hand);return hand.reduce((n,c)=>n+Math.max(0,c.rank-12),0)+[...groups.values()].reduce((n,g)=>n+(g.length===4?9:g.length===3?3:0),0);}
function ddzChoice(state,seat){
 if(state.phase==='bidding')return {type:'bid',bid:ddzStrength(state.hands[seat])>=13};
 const target=state.lastPlay?.seat===seat?null:state.lastPlay?.pattern,plays=legalDoudizhuPlays(state.hands[seat],target);if(!plays.length)return {type:'pass'};
 const finish=plays.find(p=>p.cardIds.length===state.hands[seat].length);if(finish)return finish;
 const ally=target&&seat!==state.landlord&&state.lastPlay.seat!==state.landlord;if(ally)return {type:'pass'};
 if(target){const opponentClose=state.hands.some((h,i)=>i!==seat&&(seat===state.landlord||i===state.landlord)&&h.length<=2);return [...plays].sort((a,b)=>{const tier=p=>p.pattern.type==='rocket'?2:p.pattern.type==='bomb'?1:0;return tier(a)-tier(b)||(opponentClose&&target.type==='single'?b.pattern.key-a.pattern.key:a.pattern.key-b.pattern.key);})[0];}
 const value=p=>{const ids=new Set(p.cardIds),rest=state.hands[seat].filter(c=>!ids.has(c.id)),groups=groupRanks(rest),singles=[...groups.values()].filter(g=>g.length===1).length;return p.cardIds.length*4-singles*1.6-p.pattern.key*.15-(['bomb','rocket'].includes(p.pattern.type)?10:0);};
 return [...plays].sort((a,b)=>value(b)-value(a))[0];
}

function createDoudizhu(options){
 const human=Number.isInteger(options.humanSeat)?Math.max(0,Math.min(2,options.humanSeat)):0,random=options.random||Math.random;let state;
 function restart(){const deck=shuffle(makeDoudizhuDeck(),random);state={kind:'doudizhu',phase:'bidding',turn:human,hands:[0,1,2].map(i=>deck.slice(i*17,i*17+17).sort(cardSort)),bottom:deck.slice(51),bids:[],landlord:null,lastPlay:null,passes:0,history:[],played:[],winner:null,message:'选一选，叫地主还是不叫。',messageEn:'Choose whether to call landlord.'};return getState();}
 function announce(zh,en){state.message=zh;state.messageEn=en;}
 function awardLandlord(seat){state.landlord=seat;state.hands[seat].push(...state.bottom);state.hands[seat].sort(cardSort);state.turn=seat;state.phase='playing';announce(`玩家 ${seat+1} 是地主，先出牌。`,`Player ${seat+1} is the landlord and leads.`);}
 function execute(action,seat){
  if(state.phase==='finished'||seat!==state.turn)return {ok:false,reason:'not-your-turn',state:getState()};
  if(!action||typeof action!=='object')return {ok:false,reason:'invalid-action',state:getState()};
  if(state.phase==='bidding'){
   if(action.type!=='bid'||typeof action.bid!=='boolean')return {ok:false,reason:'bid-required',state:getState()};state.bids.push({seat,bid:action.bid});state.history.push({type:'bid',seat,bid:action.bid});
   if(action.bid)awardLandlord(seat);else if(state.bids.length===3){const bots=[0,1,2].filter(i=>i!==human).sort((a,b)=>ddzStrength(state.hands[b])-ddzStrength(state.hands[a]));awardLandlord(bots[0]);}else{state.turn=(seat+1)%3;announce(`玩家 ${seat+1} 不叫。`,`Player ${seat+1} declines.`);}return {ok:true,state:getState()};
  }
  const target=state.lastPlay?.seat===seat?null:state.lastPlay?.pattern;
  if(action.type==='pass'){
   if(!target)return {ok:false,reason:'must-lead',state:getState()};state.passes++;state.history.push({type:'pass',seat});if(state.passes===2){state.turn=state.lastPlay.seat;state.lastPlay=null;state.passes=0;announce('两家不出，重新领出。','Two passes. The last player leads a new trick.');}else{state.turn=(seat+1)%3;announce(`玩家 ${seat+1} 过牌。`,`Player ${seat+1} passes.`);}return {ok:true,state:getState()};
  }
  if(action.type!=='play'||!Array.isArray(action.cardIds)||new Set(action.cardIds).size!==action.cardIds.length)return {ok:false,reason:'invalid-selection',state:getState()};
  const cards=action.cardIds.map(id=>state.hands[seat].find(c=>c.id===id));if(cards.some(c=>!c))return {ok:false,reason:'not-in-hand',state:getState()};const pattern=classifyDoudizhu(cards);if(!pattern)return {ok:false,reason:'invalid-pattern',state:getState()};if(!beatsDoudizhu(pattern,target))return {ok:false,reason:'must-beat',state:getState()};
  const ids=new Set(action.cardIds);state.hands[seat]=state.hands[seat].filter(c=>!ids.has(c.id));state.lastPlay={seat,cards:cards.sort(cardSort),pattern};state.passes=0;state.played.push(...cards);state.history.push({type:'play',seat,cards:clone(cards),pattern});state.turn=(seat+1)%3;announce(`玩家 ${seat+1} 出了${pattern.name}。`,`Player ${seat+1} plays ${pattern.nameEn}.`);
  if(!state.hands[seat].length){const team=seat===state.landlord?'landlord':'farmers';state.winner={seat,team,humanWon:(human===state.landlord)===(team==='landlord')};state.phase='finished';announce(team==='landlord'?'地主获胜。':'农民合作获胜。',team==='landlord'?'The landlord wins.':'The farmers win together.');}return {ok:true,state:getState()};
 }
 function getState(){const humanTurn=state.turn===human&&state.phase!=='finished',target=state.lastPlay?.seat===human?null:state.lastPlay?.pattern;const actions=!humanTurn?[]:state.phase==='bidding'?[{type:'bid',bid:true,label:'叫地主',labelEn:'Call landlord'},{type:'bid',bid:false,label:'不叫',labelEn:'Decline'}]:[...legalDoudizhuPlays(state.hands[human],target),...(target?[{type:'pass',label:'过牌',labelEn:'Pass'}]:[])];return {kind:'doudizhu',phase:state.phase,action:state.phase==='bidding'?'bid':state.phase==='finished'?'finished':'play',humanSeat:human,humanTurn,turn:state.turn,finished:state.phase==='finished',hand:clone(state.hands[human]),players:state.hands.map((hand,seat)=>({seat,handCount:hand.length,role:state.landlord===null?null:seat===state.landlord?'landlord':'farmer',melds:[]})),landlord:state.landlord,bottom:state.landlord===null?[]:clone(state.bottom),bottomCount:3,bids:clone(state.bids),lastPlay:clone(state.lastPlay),discard:clone(state.played),history:clone(state.history.slice(-40)),winner:clone(state.winner),legalActions:actions,suggestedAction:humanTurn?clone(ddzChoice(state,human)):null,message:state.message,messageEn:state.messageEn};}
 const game={getState,play:action=>execute(action,human),computerMove(){if(state.turn===human||state.phase==='finished')return {ok:false,reason:'waiting-for-human',state:getState()};return execute(ddzChoice(state,state.turn),state.turn);},restart};
 if(options.debug){game.debugState=()=>clone(state);game.setDebugState=value=>{state=clone(value);return getState();};}
 restart();return game;
}

const HONORS=['东','南','西','北','中','发','白'],HONORS_EN=['East','South','West','North','Red','Green','White'];
export const makeMahjongTiles=()=>Array.from({length:136},(_,id)=>{const type=Math.floor(id/4),suit=Math.floor(type/9),rank=type%9+1;return {id,type,rank:type<27?rank:null,suit:type<27?['wan','bamboo','dots'][suit]:'honor',label:type<27?rank+['万','条','筒'][suit]:HONORS[type-27],labelEn:type<27?rank+' '+['Wan','Bamboo','Dots'][suit]:HONORS_EN[type-27]};});
const tileSort=(a,b)=>a.type-b.type||a.id-b.id;
const tileCounts=tiles=>{const counts=Array(34).fill(0);for(const tile of tiles){const type=typeof tile==='number'?tile:tile?.type;if(!Number.isInteger(type)||type<0||type>33)return null;counts[type]++;if(counts[type]>4)return null;}return counts;};
export function mahjongWin(tiles,openMelds=0){
 if(!Array.isArray(tiles))return null;
 const count=Array.isArray(openMelds)?openMelds.length:openMelds,c=tileCounts(tiles);if(!c||!Number.isInteger(count)||count<0||count>4||tiles.length!==14-count*3)return null;
 if(count===0){if(c.every(n=>n%2===0))return {kind:'seven-pairs'};const orphans=[0,8,9,17,18,26,27,28,29,30,31,32,33];if(orphans.every(t=>c[t]>=1)&&c.every((n,t)=>!n||orphans.includes(t)))return {kind:'thirteen-orphans'};}
 const memo=new Map();function sets(left){const first=left.findIndex(n=>n);if(first<0)return true;const key=left.join('');if(memo.has(key))return memo.get(key);let win=false;if(left[first]>=3){left[first]-=3;win=sets(left);left[first]+=3;}if(!win&&first<27&&first%9<=6&&left[first+1]&&left[first+2]){left[first]--;left[first+1]--;left[first+2]--;win=sets(left);left[first]++;left[first+1]++;left[first+2]++;}memo.set(key,win);return win;}
 for(let pair=0;pair<34;pair++)if(c[pair]>=2){c[pair]-=2;const win=sets(c);c[pair]+=2;if(win)return {kind:'standard'};}return null;
}
function mahjongPotential(tiles){const c=tileCounts(tiles);if(!c)return -Infinity;let score=0;for(let t=0;t<34;t++){if(c[t]>=3)score+=8;if(c[t]>=2)score+=3;else if(c[t]===1&&t>=27)score-=1;if(t<27){if(t%9<=7)score+=Math.min(c[t],c[t+1])*1.8;if(t%9<=6){score+=Math.min(c[t],c[t+2])*.7;if(c[t]&&c[t+1]&&c[t+2])score+=4;}}}return score;}
function chiOptions(hand,tile){if(tile.type>=27)return [];const options=[];for(let start=tile.type-2;start<=tile.type;start++){if(start<0||start>=27||start%9>6||Math.floor(start/9)!==Math.floor(tile.type/9))continue;const needed=[start,start+1,start+2].filter(t=>t!==tile.type),cards=needed.map(type=>hand.find(t=>t.type===type));if(cards.every(Boolean))options.push({type:'claim',kind:'chi',tileIds:cards.map(t=>t.id),label:'吃 '+[start,start+1,start+2].map(t=>t%9+1).join(''),labelEn:'Chow '+[start,start+1,start+2].map(t=>t%9+1).join('')});}return options;}

function createMahjong(options){
 const human=Number.isInteger(options.humanSeat)?Math.max(0,Math.min(3,options.humanSeat)):0,random=options.random||Math.random;let state;
 const announce=(zh,en)=>{state.message=zh;state.messageEn=en;};
 function restart(){const deck=shuffle(makeMahjongTiles(),random),hands=[0,1,2,3].map(i=>deck.slice(i*13,i*13+13).sort(tileSort));state={kind:'mahjong',phase:'playing',turn:0,dealer:0,hands,melds:[[],[],[],[]],discards:[],wall:deck.slice(52),pending:null,lastDraw:null,canKong:true,winner:null,result:null,history:[],message:'摸一张，打一张，慢慢把牌凑齐。',messageEn:'Draw and discard to bring your hand together.'};drawTile(0);return getState();}
 function drawTile(seat,replacement=false){if(!state.wall.length){state.phase='finished';state.result='draw';state.pending=null;announce('牌墙用尽，荒庄。','The wall is empty. This hand is a draw.');return false;}const tile=replacement?state.wall.pop():state.wall.shift();state.hands[seat].push(tile);state.hands[seat].sort(tileSort);state.turn=seat;state.phase='playing';state.lastDraw={seat,tile};state.canKong=true;state.history.push({type:'draw',seat,replacement});return true;}
 function win(seat,tile,from,source){const hand=tile?[...state.hands[seat],tile]:state.hands[seat],pattern=mahjongWin(hand,state.melds[seat].length);if(!pattern)return false;if(tile){state.hands[seat].push(tile);state.hands[seat].sort(tileSort);}state.winner={seat,kind:pattern.kind,from,source,humanWon:seat===human};state.result='win';state.phase='finished';state.pending=null;announce(`玩家 ${seat+1} 胡牌。`,`Player ${seat+1} wins.`);return true;}
 function ownActions(seat){if(state.phase!=='playing'||state.turn!==seat)return [];const hand=state.hands[seat],actions=hand.map(tile=>({type:'discard',tileId:tile.id,label:'打 '+tile.label,labelEn:'Discard '+tile.labelEn}));if(state.lastDraw?.seat===seat&&mahjongWin(hand,state.melds[seat].length))actions.unshift({type:'hu',label:'胡牌',labelEn:'Win'});if(state.canKong&&state.wall.length){const c=tileCounts(hand);for(let type=0;type<34;type++){const matches=hand.filter(t=>t.type===type);if(c[type]===4)actions.unshift({type:'kong',tileIds:matches.map(t=>t.id),kind:'concealed',label:'暗杠 '+matches[0].label,labelEn:'Concealed kong '+matches[0].labelEn});if(c[type]&&state.melds[seat].some(m=>m.kind==='peng'&&m.tiles[0].type===type))actions.unshift({type:'kong',tileIds:[matches[0].id],kind:'added',label:'加杠 '+matches[0].label,labelEn:'Added kong '+matches[0].labelEn});}}return actions;}
 function claimQueue(tile,from,rob=false){const queue=[];for(let distance=1;distance<=3;distance++){const seat=(from+distance)%4,hand=state.hands[seat];if(mahjongWin([...hand,tile],state.melds[seat].length))queue.push({seat,priority:3,distance,actions:[{type:'claim',kind:'hu',label:rob?'抢杠胡':'胡牌',labelEn:rob?'Rob kong for a win':'Win'}]});if(rob)continue;const same=hand.filter(t=>t.type===tile.type),actions=[];if(same.length>=3&&state.wall.length)actions.push({type:'claim',kind:'gang',tileIds:same.slice(0,3).map(t=>t.id),label:'明杠',labelEn:'Exposed kong'});if(same.length>=2)actions.push({type:'claim',kind:'peng',tileIds:same.slice(0,2).map(t=>t.id),label:'碰',labelEn:'Pung'});if(actions.length)queue.push({seat,priority:2,distance,actions});if(distance===1){const chi=chiOptions(hand,tile);if(chi.length)queue.push({seat,priority:1,distance,actions:chi});}}return queue.sort((a,b)=>b.priority-a.priority||a.distance-b.distance);}
 function completeAddedKong(pending){const meld=state.melds[pending.from][pending.meldIndex];meld.kind='gang';meld.tiles.push(pending.tile);meld.added=true;state.history.push({type:'kong',seat:pending.from,kind:'added',tiles:clone(meld.tiles)});state.pending=null;drawTile(pending.from,true);}
 function advanceClaim(){const pending=state.pending;if(pending.queue.length){state.phase='claim';state.turn=pending.queue[0].seat;return;}if(pending.reason==='rob-kong')completeAddedKong(pending);else{const next=(pending.from+1)%4;state.pending=null;drawTile(next);}}
 function matchesAction(action,candidate){return action.type===candidate.type&&(candidate.kind?candidate.kind===action.kind||action.type==='kong':true)&&(candidate.tileIds?[...candidate.tileIds].sort((a,b)=>a-b).join(',')===[...(action.tileIds||[])].sort((a,b)=>a-b).join(','):true)&&(candidate.tileId===undefined||candidate.tileId===action.tileId);}
 function execute(action,seat){
  if(state.phase==='finished'||state.turn!==seat)return {ok:false,reason:'not-your-turn',state:getState()};
  if(!action||typeof action!=='object')return {ok:false,reason:'invalid-action',state:getState()};
  if(state.phase==='claim'){
   const pending=state.pending,entry=pending.queue[0];if(action.type!=='claim')return {ok:false,reason:'claim-required',state:getState()};if(action.kind==='pass'){pending.queue.shift();advanceClaim();return {ok:true,state:getState()};}
   const candidate=entry.actions.find(c=>matchesAction(action,c));if(!candidate)return {ok:false,reason:'invalid-claim',state:getState()};
   if(action.kind==='hu'){if(pending.discardIndex!==undefined)state.discards[pending.discardIndex].claimedBy=seat;win(seat,pending.tile,pending.from,pending.reason==='rob-kong'?'rob-kong':'discard');return {ok:true,state:getState()};}
   const ids=new Set(candidate.tileIds),tiles=state.hands[seat].filter(t=>ids.has(t.id));state.hands[seat]=state.hands[seat].filter(t=>!ids.has(t.id));tiles.push(pending.tile);tiles.sort(tileSort);state.melds[seat].push({kind:action.kind,tiles,from:pending.from,concealed:false});state.discards[pending.discardIndex].claimedBy=seat;state.history.push({type:'claim',seat,kind:action.kind,tiles:clone(tiles)});state.pending=null;state.turn=seat;state.phase='playing';state.lastDraw=null;state.canKong=false;if(action.kind==='gang')drawTile(seat,true);announce(`玩家 ${seat+1} ${action.kind==='chi'?'吃':action.kind==='peng'?'碰':'杠'}牌。`,`Player ${seat+1} claims ${action.kind==='chi'?'chow':action.kind==='peng'?'pung':'kong'}.`);return {ok:true,state:getState()};
  }
  const candidate=ownActions(seat).find(c=>matchesAction(action,c));if(!candidate)return {ok:false,reason:'illegal-action',state:getState()};
  if(action.type==='hu'){win(seat,null,null,'self-draw');return {ok:true,state:getState()};}
  if(action.type==='kong'){
   const ids=new Set(candidate.tileIds),tiles=state.hands[seat].filter(t=>ids.has(t.id));state.hands[seat]=state.hands[seat].filter(t=>!ids.has(t.id));if(candidate.kind==='concealed'){state.melds[seat].push({kind:'gang',tiles,concealed:true,from:seat});state.history.push({type:'kong',seat,kind:'concealed'});drawTile(seat,true);}else{const meldIndex=state.melds[seat].findIndex(m=>m.kind==='peng'&&m.tiles[0].type===tiles[0].type);state.pending={reason:'rob-kong',tile:tiles[0],from:seat,meldIndex,queue:claimQueue(tiles[0],seat,true)};advanceClaim();}return {ok:true,state:getState()};
  }
  const index=state.hands[seat].findIndex(t=>t.id===candidate.tileId),[tile]=state.hands[seat].splice(index,1),discardIndex=state.discards.length;state.discards.push({seat,tile,claimedBy:null});state.history.push({type:'discard',seat,tile:clone(tile)});state.lastDraw=null;state.pending={reason:'discard',tile,from:seat,discardIndex,queue:claimQueue(tile,seat)};announce(`玩家 ${seat+1} 打出${tile.label}。`,`Player ${seat+1} discards ${tile.labelEn}.`);advanceClaim();return {ok:true,state:getState()};
 }
 function choice(seat){
  if(state.phase==='claim'){const actions=state.pending.queue[0].actions,winning=actions.find(a=>a.kind==='hu');if(winning)return winning;const hand=state.hands[seat],before=mahjongPotential(hand);const scored=actions.map(action=>({action,score:mahjongPotential(hand.filter(t=>!action.tileIds.includes(t.id)))+11})).sort((a,b)=>b.score-a.score);return scored[0]?.score>=before?scored[0].action:{type:'claim',kind:'pass'};}
  const actions=ownActions(seat),winning=actions.find(a=>a.type==='hu');if(winning)return winning;const kong=actions.find(a=>a.type==='kong');if(kong)return kong;return actions.filter(a=>a.type==='discard').map(action=>({action,score:mahjongPotential(state.hands[seat].filter(t=>t.id!==action.tileId))})).sort((a,b)=>b.score-a.score||a.action.tileId-b.action.tileId)[0]?.action;
 }
 function getState(){const humanTurn=state.turn===human&&state.phase!=='finished',actions=!humanTurn?[]:state.phase==='claim'?[...state.pending.queue[0].actions,{type:'claim',kind:'pass',label:'过',labelEn:'Pass'}]:ownActions(human);return {kind:'mahjong',phase:state.phase,action:state.phase==='claim'?'claim':state.phase==='finished'?'finished':'discard',humanSeat:human,humanTurn,turn:state.turn,finished:state.phase==='finished',dealer:state.dealer,hand:clone(state.hands[human]),players:state.hands.map((hand,seat)=>({seat,handCount:hand.length,melds:state.melds[seat].map(m=>m.concealed&&seat!==human?{kind:'gang',concealed:true,tileCount:4,tiles:[]}:clone(m)),discards:state.discards.filter(d=>d.seat===seat&&d.claimedBy===null).map(d=>clone(d.tile))})),discard:clone(state.discards),wallCount:state.wall.length,pending:state.pending?{reason:state.pending.reason,tile:clone(state.pending.tile),from:state.pending.from}:null,lastDraw:state.lastDraw?.seat===human?clone(state.lastDraw.tile):null,history:clone(state.history.slice(-40)),winner:clone(state.winner),result:state.result,legalActions:clone(actions),suggestedAction:humanTurn?clone(choice(human)):null,message:state.message,messageEn:state.messageEn};}
 const game={getState,play:action=>execute(action,human),computerMove(){if(state.turn===human||state.phase==='finished')return {ok:false,reason:'waiting-for-human',state:getState()};const action=choice(state.turn);if(!action)return {ok:false,reason:'no-action',state:getState()};return execute(action,state.turn);},restart};if(options.debug){game.debugState=()=>clone(state);game.setDebugState=value=>{state=clone(value);return getState();};}restart();return game;
}

export function createCardGame(kind,options={}){if(['doudizhu','dou-dizhu','ddz'].includes(kind))return createDoudizhu(options);if(kind==='mahjong')return createMahjong(options);throw new Error('Unknown card game: '+kind);}
