import {raiseDialog,consumeDialogEscape} from './dialog-stack.js';
const CHANNELS=[{id:'d-NUlz3FXpw',title:'达令港的烟花',caption:'Darling Harbour · 烟花影像',source:'https://www.youtube.com/watch?v=d-NUlz3FXpw'},{id:'8Ff5rpgoWWM',title:'海港大桥 · 跨年烟花',caption:'City of Sydney · 2024 年跨年烟花官方完整版',source:'https://www.youtube.com/watch?v=8Ff5rpgoWWM'}];
export function setupTelevision({THREE,scene,model,camera,register,go,toast}){
 const normalize=s=>s.replaceAll('_',' ').toLowerCase();let surface=null,body=null;model.traverse(o=>{if(!o.isMesh)return;if(normalize(o.name)==='tv image surface')surface=o;if(normalize(o.name)==='large television')body=o;});
 if(!surface)return {open(){toast('电视还没有找到。');},close(){},update(){},dispose(){}};
 const group=new THREE.Group();group.name='Interactive Sydney television';scene.add(group);group.attach(surface);if(body)group.attach(body);group.updateMatrixWorld(true);const bounds=new THREE.Box3().setFromObject(surface),z=bounds.min.z-.006;
 const corners=[new THREE.Vector3(bounds.max.x,bounds.max.y,z),new THREE.Vector3(bounds.min.x,bounds.max.y,z),new THREE.Vector3(bounds.min.x,bounds.min.y,z),new THREE.Vector3(bounds.max.x,bounds.min.y,z)];
 const canvas=document.createElement('canvas');canvas.width=1024;canvas.height=526;const ctx=canvas.getContext('2d');ctx.fillStyle='#263c40';ctx.fillRect(0,0,1024,526);ctx.fillStyle='#789296';ctx.fillRect(0,345,1024,181);ctx.strokeStyle='#b5c5ad';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(60,333);ctx.quadraticCurveTo(400,50,745,333);ctx.stroke();for(let i=0;i<11;i++){const x=85+i*57,y=176+Math.pow((x-410)/28,2);ctx.beginPath();ctx.moveTo(x,Math.min(333,y));ctx.lineTo(x,333);ctx.stroke();}ctx.fillStyle='#f1e9cb';ctx.font='600 72px sans-serif';ctx.fillText('窗外，是悉尼。',130,430);ctx.font='26px sans-serif';ctx.fillStyle='#c2d0bd';ctx.fillText('轻点电视  ·  让烟花陪你坐一会儿',130,480);const tx=new THREE.CanvasTexture(canvas);tx.colorSpace=THREE.SRGBColorSpace;
 // The GLB's visible -Z box face runs U from viewer-right to viewer-left.
 // Mirror only this texture's U transform; keep V and the DOM video projection unchanged.
 tx.repeat.x=-1;tx.offset.x=1;surface.material=new THREE.MeshBasicMaterial({map:tx,color:0xffffff});
 // Each original box face gets a standby image; the video itself uses its true front plane.
 let on=false,theatre=true,channel=0,panel=null,player=null,overlay=null,localURL=null,ytPlayer=null,playerSource=null,connection=null,connectionTimer=null,apiPromise=null;
 const make=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;};
 function button(text,fn,cls='world-button'){const b=make('button',cls,text);b.onclick=fn;return b;}
 function clearPlayer(){clearTimeout(connectionTimer);connection?.remove();connection=null;try{ytPlayer?.destroy();}catch{}ytPlayer=null;player?.remove();player=null;playerSource=null;if(localURL){URL.revokeObjectURL(localURL);localURL=null;}}
 function youtubeAPI(){if(window.YT?.Player)return Promise.resolve(window.YT);if(apiPromise)return apiPromise;apiPromise=new Promise((resolve,reject)=>{const script=document.createElement('script');const timer=setTimeout(()=>reject(Error('timeout')),10000);window.onYouTubeIframeAPIReady=()=>{clearTimeout(timer);resolve(window.YT);};script.src='https://www.youtube.com/iframe_api';script.onerror=()=>{clearTimeout(timer);reject(Error('network'));};document.head.append(script);}).catch(e=>{apiPromise=null;throw e;});return apiPromise;}
 function connectionNotice(host){connection=make('div','tv-connection');const title=make('strong','','正在连接悉尼的画面……'),hint=make('span','','播放器由原平台提供，请稍等一会儿。');const link=make('a','world-button','去原平台观看 ↗');link.href=CHANNELS[channel].source;link.target='_blank';link.rel='noopener noreferrer';connection.append(title,hint,link);host.append(connection);return (failed=false)=>{if(!connection)return;if(failed){connection.hidden=false;title.textContent='画面暂时没有连上';hint.textContent='可以去原平台继续观看，也可以播放自己的视频文件。';}else{connection.hidden=true;}};}
 function mount(host){if(player&&(playerSource===channel||playerSource==='local')){host.append(player);if(connection)host.append(connection);return;}clearPlayer();playerSource=channel;player=document.createElement('iframe');player.title=CHANNELS[channel].title+' · YouTube';player.src=`https://www.youtube.com/embed/${CHANNELS[channel].id}?autoplay=1&mute=1&playsinline=1&rel=0&loop=1&playlist=${CHANNELS[channel].id}&enablejsapi=1&origin=${encodeURIComponent(location.origin)}`;player.allow='autoplay; encrypted-media; fullscreen; picture-in-picture';player.referrerPolicy='strict-origin-when-cross-origin';player.allowFullscreen=true;host.append(player);const iframe=player,notice=connectionNotice(host);let frameLoaded=false;iframe.addEventListener('load',()=>{if(player===iframe){frameLoaded=true;clearTimeout(connectionTimer);notice();}});connectionTimer=setTimeout(()=>{if(player===iframe)notice(true);},10000);youtubeAPI().then(YT=>{if(player!==iframe)return;ytPlayer=new YT.Player(iframe,{events:{onReady:e=>{if(player!==iframe)return;frameLoaded=true;clearTimeout(connectionTimer);notice();e.target.mute();e.target.playVideo();},onError:()=>{if(player===iframe){clearTimeout(connectionTimer);notice(true);}},onStateChange:e=>{if(player===iframe&&e.data===1){clearTimeout(connectionTimer);notice();}}}});}).catch(()=>{if(player===iframe&&!frameLoaded)notice(true);});}
 function close(){on=false;panel?.remove();panel=null;overlay?.remove();overlay=null;clearPlayer();}
 function open(){if(on){panel?.focus();return;}on=true;theatre=true;go('television');draw();}
 function draw(){if(playerSource!=='local')clearPlayer();else player?.remove();connection?.remove();panel?.remove();overlay?.remove();overlay=null;panel=make('section','home-dialog tv-window'+(theatre?'':' tv-remote'));panel.dataset.homeUi='';panel.style.zIndex=180;panel.tabIndex=-1;panel.setAttribute('role','dialog');panel.setAttribute('aria-label','电视 · 窗外是悉尼');panel.style.setProperty('--dialog-width',theatre?'850px':'440px');const header=make('header','dialog-header'),title=make('div');title.append(make('h2','','窗外，是悉尼。'),make('p','','坐一会儿，看看海港和烟花。'));const x=button('×',close,'dialog-close');x.setAttribute('aria-label','关闭电视');header.append(title,x);const body=make('div','dialog-body'),channels=make('div','tv-toolbar');CHANNELS.forEach((c,i)=>channels.append(button(c.title,()=>{clearPlayer();channel=i;draw();},'tv-channel'+(channel===i?' active':''))));body.append(channels);const viewport=make('div','tv-player');if(theatre){body.append(viewport);mount(viewport);}else{overlay=make('div','tv-overlay');overlay.hidden=true;document.body.append(overlay);mount(overlay);body.append(make('p','tv-status','播放器已放到客厅的电视屏幕上。旋转或靠近看看，也可以放大观看。'));panel.style.left='auto';panel.style.right='20px';panel.style.transform='none';panel.style.top='auto';panel.style.bottom='110px';}
 const actions=make('div','world-actions');actions.append(button(theatre?'放回电视屏幕':'放大观看',()=>{theatre=!theatre;draw();}),button('关电视',close));const source=make('a','world-button','原平台打开 ↗');source.href=CHANNELS[channel].source;source.target='_blank';source.rel='noopener noreferrer';actions.append(source);body.append(actions,make('p','tv-credit',CHANNELS[channel].caption+'。初始静音，播放器内可以打开声音。若原平台暂时未载入，可用上方入口观看。'));
 const local=document.createElement('input');local.type='file';local.accept='video/*';local.hidden=true;const localButton=button('播放自己的视频文件',()=>local.click());local.onchange=()=>{const f=local.files?.[0];if(!f)return;if(!f.type.startsWith('video/')&&!/\.(mp4|webm|mov|m4v)$/i.test(f.name)){toast('请选择一个视频文件。');return;}clearPlayer();playerSource='local';localURL=URL.createObjectURL(f);player=document.createElement('video');player.src=localURL;player.controls=true;player.playsInline=true;player.loop=true;player.style.width='100%';player.style.height='100%';(theatre?viewport:overlay).append(player);player.play().catch(()=>toast('按一下播放器里的播放键就好。'));};body.append(localButton,local);panel.append(header,body);document.body.append(panel);raiseDialog(panel);panel.addEventListener('pointerdown',()=>raiseDialog(panel));panel.addEventListener('focusin',()=>raiseDialog(panel));panel.focus();}
 // Exact projective mapping of the rectangular screen to the perspective camera.
 function homography(points){const A=[],b=[];[[0,0],[640,0],[640,360],[0,360]].forEach(([u,v],i)=>{const{x,y}=points[i];A.push([u,v,1,0,0,0,-x*u,-x*v]);b.push(x);A.push([0,0,0,u,v,1,-y*u,-y*v]);b.push(y);});for(let c=0;c<8;c++){let p=c;for(let r=c+1;r<8;r++)if(Math.abs(A[r][c])>Math.abs(A[p][c]))p=r;if(Math.abs(A[p][c])<1e-10)return null;[A[p],A[c]]=[A[c],A[p]];[b[p],b[c]]=[b[c],b[p]];const q=A[c][c];for(let j=c;j<8;j++)A[c][j]/=q;b[c]/=q;for(let r=0;r<8;r++){if(r===c)continue;const n=A[r][c];for(let j=c;j<8;j++)A[r][j]-=n*A[c][j];b[r]-=n*b[c];}}return[b[0],b[3],0,b[6],b[1],b[4],0,b[7],0,0,1,0,b[2],b[5],0,1];}
 const centre=bounds.getCenter(new THREE.Vector3()),ray=new THREE.Raycaster();let frame=0;
 function update(){if(!on||theatre||!overlay)return;const projected=corners.map(p=>p.clone().project(camera));let visible=camera.position.z<z-.08&&projected.every(p=>p.z>-1&&p.z<1);const pixels=projected.map(v=>({x:(v.x*.5+.5)*innerWidth,y:(-v.y*.5+.5)*innerHeight}));if(Math.hypot(pixels[0].x-pixels[1].x,pixels[0].y-pixels[1].y)<100)visible=false;
  if(visible&&frame++%8===0){const dir=centre.clone().sub(camera.position);ray.set(camera.position,dir.clone().normalize());ray.far=dir.length()-.015;const hit=ray.intersectObjects(scene.children,true).find(h=>{if(h.object===surface||h.object===body)return false;let p=h.object;while(p){if(!p.visible)return false;p=p.parent;}return !h.object.material?.transparent&&h.object.userData.category!=='rug';});overlay.dataset.occluded=String(!!hit);}
  visible=visible&&overlay.dataset.occluded!=='true';const matrix=visible?homography(pixels):null;overlay.hidden=!matrix;if(matrix)overlay.style.transform='matrix3d('+matrix.join(',')+')';
 }
 const esc=e=>{if(on&&consumeDialogEscape(e,panel))close();};document.addEventListener('keydown',esc,true);register({id:'television',label:'电视 · 看看悉尼',kind:'tv',object:group,anchor:centre.clone().add(new THREE.Vector3(0,.65,-.08)),click:open});
 return {open,close,update,getStatus:()=>({on,theatre,channel:CHANNELS[channel]}),dispose(){close();document.removeEventListener('keydown',esc,true);tx.dispose();}};
}
