import test from 'node:test';
import assert from 'node:assert/strict';
import {createLaundryLifecycle,LAUNDRY_PERIOD,WASH_DURATION,DRY_DURATION} from '../laundry-lifecycle.js?v=14';

function fixture(initial={}){let at=Date.UTC(2026,8,7),state=structuredClone(initial),writes=0,calls=0;const options={getState:()=>state,setState:patch=>{state={...state,...patch};writes++;},now:()=>at,random:()=>{calls++;return .5;}};return {life:createLaundryLifecycle(options),reload:()=>createLaundryLifecycle(options),advance:ms=>at+=ms,get state(){return state;},get writes(){return writes;},get calls(){return calls;},get now(){return at;}};}
function finish(f){assert.ok(f.life.startWash().ok);f.advance(WASH_DURATION);assert.ok(f.life.transferToDryer().ok);assert.ok(f.life.startDry().ok);f.advance(DRY_DURATION);assert.ok(f.life.collect().ok);}

test('first load contains 2–5 stable random garments and refresh/reload cannot create another',()=>{const f=fixture(),first=f.life.getStatus();assert.ok(first.garments.length>=2&&first.garments.length<=5);const count=f.calls,writes=f.writes;for(let i=0;i<50;i++){assert.deepEqual(f.life.refresh().garments,first.garments);assert.equal(f.reload().getStatus().batch.id,first.batch.id);}assert.equal(f.calls,count);assert.equal(f.writes,writes);assert.equal(first.nextBatchAt,f.now+LAUNDRY_PERIOD);});

test('washing and drying need their full real durations and double clicks never restart timers',()=>{const f=fixture();f.life.getStatus();assert.equal(f.life.transferToDryer().ok,false);const wash=f.life.startWash();assert.ok(wash.ok);const washEnd=wash.state.batch.endsAt;f.advance(60000);assert.equal(f.life.startWash().ok,false);assert.equal(f.life.getStatus().batch.endsAt,washEnd);f.advance(WASH_DURATION-60001);assert.equal(f.life.getStatus().phase,'washing');assert.equal(f.life.transferToDryer().ok,false);f.advance(1);assert.equal(f.life.getStatus().phase,'washed');assert.equal(f.life.collect().ok,false);assert.ok(f.life.transferToDryer().ok);assert.equal(f.life.transferToDryer().ok,false);const dry=f.life.startDry();assert.ok(dry.ok);assert.equal(f.life.startDry().ok,false);f.advance(DRY_DURATION-1);assert.equal(f.life.collect().ok,false);f.advance(1);assert.ok(f.life.collect().ok);assert.equal(f.life.collect().ok,false);assert.equal(f.life.getStatus().collectedBatches,1);});

test('saved in-progress cycles resume after closing the page without auto-transferring or auto-collecting',()=>{const f=fixture();f.life.startWash();f.advance(WASH_DURATION+60000);const reloaded=f.reload();assert.equal(reloaded.getStatus().phase,'washed');assert.equal(reloaded.getStatus().washerOccupied,true);assert.equal(reloaded.getStatus().dryerOccupied,false);reloaded.transferToDryer();reloaded.startDry();f.advance(DRY_DURATION+60000);const again=f.reload();assert.equal(again.getStatus().phase,'dry');assert.equal(again.getStatus().collectedBatches,0);assert.equal(again.getStatus().dryerOccupied,true);});

test('fortnightly deliveries follow the original schedule and long absences do not accumulate loads',()=>{const f=fixture();const first=f.life.getStatus();finish(f);assert.equal(f.life.getStatus().phase,'empty');f.advance(first.nextBatchAt-f.now-1);assert.equal(f.life.getStatus().phase,'empty');f.advance(1);const second=f.life.getStatus();assert.equal(second.sequence,2);assert.equal(second.batch.scheduledAt,first.nextBatchAt);f.advance(17*LAUNDRY_PERIOD);assert.equal(f.life.getStatus().batch.id,second.batch.id);assert.ok(f.life.getStatus().overdueBatchWaiting);finish(f);const latest=f.life.getStatus();assert.equal(latest.sequence,3);assert.ok(latest.garments.length<=5);assert.ok(latest.nextBatchAt>f.now);assert.equal(latest.batch.scheduledAt-first.cycleAnchorAt,18*LAUNDRY_PERIOD);});

test('older backups gain one persisted load; incomplete legacy timers cannot fabricate completion',()=>{const f=fixture({notes:[],laundry:{clothes:['shirt','socks'],status:'washing'}});const first=f.life.getStatus();assert.equal(first.phase,'dirty');assert.equal(first.garments.length,2);assert.equal(first.garments[0].kind,'shirt');assert.equal(f.state.laundry.version,1);assert.equal(f.reload().getStatus().batch.id,first.batch.id);finish(f);assert.equal(f.life.getStatus().phase,'empty','legacy migration must not deliver a second load immediately');assert.equal(f.life.getStatus().nextBatchAt,first.cycleAnchorAt+LAUNDRY_PERIOD);});

test('tampered finish times cannot shorten a programme and returned snapshots cannot change stored garments',()=>{const f=fixture();f.life.startWash();f.state.laundry.batch.endsAt=f.now+1;f.advance(2);assert.equal(f.life.getStatus().phase,'washing');assert.equal(f.life.getStatus().batch.endsAt,f.state.laundry.batch.startedAt+WASH_DURATION);const result=f.life.getStatus();result.garments[0].kind='towel';assert.notEqual(f.life.getStatus().garments[0].kind,'towel');});
